function _mkQ(id, type, text, opts, min, max) {
  const q = { id: 'q_' + id, type, text, required: false };
  if (opts) q.options = opts;
  if (min !== undefined) { q.min = min; q.max = max; }
  return q;
}

function _mkQfu(id, type, text, fuYes, fuNo) {
  return { id: 'q_' + id, type, text, required: false, followUpYes: fuYes || '', followUpNo: fuNo || '' };
}

function _specialtyTemplates() {
  const E  = typeof currentLang !== 'undefined' && currentLang === 'en';
  const n  = (u, e) => E ? e : u;
  const yn = E ? ['Yes', 'No'] : ['Так', 'Ні'];

  return [

    // ════════════════════════════════════════════════════════
    // МОЗ 003/О — ПЕРВИННИЙ ОГЛЯД
    // ════════════════════════════════════════════════════════
    {
      icon: '🏥', color: '#3B82F6',
      name: n('МОЗ 003/о — Первинний огляд', 'MOH 003/o — Initial Examination'),
      templates: [
        {
          key: 'moz_003_primary',
          badge: 'main',
          name: n('Первинний огляд (МОЗ 003/о)', 'Initial Examination (MOH 003/o)'),
          desc: n('Повна форма первинного огляду за стандартом МОЗ України — скарги, анамнез, об\'єктивний статус', 'Full MOH Ukraine initial examination form'),
          questions: [

            // ── СКАРГИ ──────────────────────────────────────
            _mkQ('moz_c1', 'text',
              n('Основна скарга — головна причина звернення:', 'Chief complaint — main reason for visit:')),
            _mkQ('moz_c2', 'text',
              n('Додаткові скарги (супутні симптоми):', 'Additional complaints (associated symptoms):')),

            // ── АНАМНЕЗ ЗАХВОРЮВАННЯ ─────────────────────────
            _mkQ('moz_am1', 'text',
              n('Початок захворювання — коли і як почалось (дата, гострий чи поступовий початок):', 'Disease onset — when and how it started (date, acute or gradual):')),
            _mkQ('moz_am2', 'choice',
              n('Динаміка стану з моменту початку:', 'Condition dynamics since onset:'),
              n(['Погіршення', 'Без змін', 'Покращення', 'Хвилеподібний перебіг'],
                ['Worsening', 'No change', 'Improvement', 'Fluctuating'])),
            _mkQ('moz_am3', 'text',
              n('Динаміка детальніше (як змінювались симптоми з часом):', 'Dynamics in detail (how symptoms changed over time):')),
            _mkQ('moz_am4', 'text',
              n('Локалізація симптомів (де саме: ділянка тіла або орган):', 'Symptom location (body area or organ):')),
            _mkQ('moz_am5', 'text',
              n('Характер симптому (тупий / гострий / пекучий / ниючий):', 'Symptom character (dull / sharp / burning / aching):')),
            _mkQ('moz_am6', 'scale',
              n('Інтенсивність болю або основного симптому (0–10):', 'Pain / symptom intensity (0–10):'),
              null, 0, 10),
            _mkQ('moz_am7', 'text',
              n('Тривалість нападів або симптомів (постійно / нападами / скільки хв):', 'Duration of episodes (constant / intermittent / minutes):')),
            _mkQ('moz_am8', 'text',
              n('Що провокує або посилює симптоми:', 'What triggers or worsens symptoms:')),
            _mkQ('moz_am9', 'text',
              n('Що полегшує симптоми (спокій, тепло, певна поза, ліки):', 'What relieves symptoms (rest, warmth, position, medications):')),
            _mkQ('moz_am10', 'text',
              n('Попереднє лікування з приводу цього захворювання (що, коли, який ефект):', 'Previous treatment for this condition (what, when, effect):')),
            _mkQ('moz_am11', 'text',
              n('Попередні обстеження (аналізи, УЗД, ЕКГ — результати якщо відомі):', 'Previous investigations (labs, ultrasound, ECG — results if known):')),

            // ── АНАМНЕЗ ЖИТТЯ ────────────────────────────────
            _mkQ('moz_av1', 'text',
              n('Перенесені та хронічні захворювання (перелік, рік встановлення діагнозу):', 'Past and chronic conditions (list, year diagnosed):')),
            _mkQ('moz_av2', 'text',
              n('Операції та госпіталізації (що, рік, ускладнення):', 'Surgeries and hospitalisations (what, year, complications):')),
            _mkQ('moz_av3', 'text',
              n('Травми (переломи, ЧМТ — коли, наслідки):', 'Injuries (fractures, head trauma — when, consequences):')),
            _mkQ('moz_av4', 'text',
              n('Постійні препарати (назва, доза, як довго приймає):', 'Regular medications (name, dose, duration):')),
            { id: 'q_moz_av5', type: 'yesno', text: n('Переливання крові (гемотрансфузії):', 'Blood transfusions:'), required: false,
              followUpYes: n('Коли і у зв\'язку з чим:', 'When and why:'), followUpNo: '' },
            _mkQ('moz_av6', 'text',
              n('Спадковість — захворювання у близьких родичів (батьки, брати/сестри):', 'Hereditary — conditions in close relatives (parents, siblings):')),
            { id: 'q_moz_av7', type: 'yesno', text: n('Паління (тютюн, IQOS, електронні сигарети):', 'Smoking (tobacco, IQOS, e-cigarettes):'), required: false,
              followUpYes: n('Скільки сигарет на день і як довго (пачко-роки):', 'Cigarettes per day and how long (pack-years):'), followUpNo: '' },
            { id: 'q_moz_av8', type: 'yesno', text: n('Вживання алкоголю:', 'Alcohol use:'), required: false,
              followUpYes: n('Частота і обсяг:', 'Frequency and amount:'), followUpNo: '' },
            _mkQ('moz_av9', 'text',
              n('Професія та умови праці (шкідливості: хімія, пил, шум, нічні зміни):', 'Occupation and working conditions (hazards: chemicals, dust, noise, night shifts):')),
            _mkQ('moz_av10', 'text',
              n('Фізична активність (тип і частота):', 'Physical activity (type and frequency):')),

            // ── АЛЕРГОЛОГІЧНИЙ АНАМНЕЗ ───────────────────────
            { id: 'q_moz_al1', type: 'yesno', text: n('Алергія на лікарські препарати:', 'Drug allergies:'), required: false,
              followUpYes: n('Назва препарату та характер реакції (висипка, набряк, анафілаксія):', 'Drug name and reaction type (rash, oedema, anaphylaxis):'), followUpNo: '' },
            { id: 'q_moz_al2', type: 'yesno', text: n('Харчова алергія або непереносимість:', 'Food allergy or intolerance:'), required: false,
              followUpYes: n('Які продукти та яка реакція:', 'Which foods and what reaction:'), followUpNo: '' },
            { id: 'q_moz_al3', type: 'yesno', text: n('Інші алергічні реакції (пил, пилок, тварини, латекс):', 'Other allergies (dust, pollen, animals, latex):'), required: false,
              followUpYes: n('Алерген та прояви:', 'Allergen and manifestations:'), followUpNo: '' },

            // ── ОБ'ЄКТИВНИЙ СТАТУС ───────────────────────────
            _mkQ('moz_ob1', 'choice',
              n('Загальний стан пацієнта:', 'General condition:'),
              n(['Задовільний', 'Середньої тяжкості', 'Тяжкий', 'Вкрай тяжкий'],
                ['Satisfactory', 'Moderate severity', 'Severe', 'Critical'])),
            _mkQ('moz_ob2', 'choice',
              n('Свідомість:', 'Consciousness:'),
              n(['Ясна', 'Оглушення', 'Сопор', 'Кома'],
                ['Clear', 'Obtunded', 'Stupor', 'Coma'])),
            _mkQ('moz_ob3', 'choice',
              n('Положення:', 'Position:'),
              n(['Активне', 'Пасивне', 'Вимушене'],
                ['Active', 'Passive', 'Forced'])),
            _mkQ('moz_ob4', 'text',
              n('Ріст (см) / Вага (кг) / ІМТ (кг/м²):', 'Height (cm) / Weight (kg) / BMI (kg/m²):')),
            _mkQ('moz_ob5', 'text',
              n('Температура тіла (°C):', 'Body temperature (°C):')),
            _mkQ('moz_ob6', 'text',
              n('АТ на правій руці / лівій руці (мм рт.ст.):', 'BP right arm / left arm (mmHg):')),
            _mkQ('moz_ob7', 'text',
              n('Пульс (уд/хв), ритм (ритмічний / аритмічний):', 'Pulse (bpm), rhythm (regular / irregular):')),
            _mkQ('moz_ob8', 'text',
              n('ЧДД (за хв) / SpO₂ (%):', 'RR (per min) / SpO₂ (%):')),
            _mkQ('moz_ob9', 'text',
              n('Шкіра та слизові (колір, вологість, висипка, набряки):', 'Skin and mucous membranes (colour, moisture, rash, oedema):')),
            _mkQ('moz_ob10', 'text',
              n('Серцево-судинна система (тони, шуми, межі серця):', 'Cardiovascular system (heart sounds, murmurs, borders):')),
            _mkQ('moz_ob11', 'text',
              n('Органи дихання (перкусія, аускультація, хрипи):', 'Respiratory system (percussion, auscultation, crackles):')),
            _mkQ('moz_ob12', 'text',
              n('Органи черевної порожнини (живіт, болючість, печінка, селезінка):', 'Abdomen (tenderness, liver, spleen):')),
            _mkQ('moz_ob13', 'text',
              n('Нервова система (орієнтація, координація, менінгеальні знаки):', 'Nervous system (orientation, coordination, meningeal signs):')),
            _mkQ('moz_ob14', 'text',
              n('Інші знахідки при огляді:', 'Other findings on examination:')),

            // ── ДІАГНОЗ ──────────────────────────────────────
            _mkQ('moz_dx1', 'text',
              n('Попередній діагноз (основний) за МКХ-10 — код і назва:', 'Preliminary diagnosis (main) per ICD-10 — code and name:')),
            _mkQ('moz_dx2', 'text',
              n('Супутні захворювання / конкурентні діагнози за МКХ-10:', 'Concomitant conditions / competing diagnoses per ICD-10:')),
            _mkQ('moz_dx3', 'text',
              n('Ускладнення основного захворювання (якщо є):', 'Complications of main condition (if any):')),

            // ── ПЛАН ОБСТЕЖЕННЯ ───────────────────────────────
            _mkQ('moz_pl1', 'text',
              n('Лабораторні дослідження (ЗАК, ЗАС, біохімія, коагулограма тощо):', 'Laboratory tests (CBC, urinalysis, biochemistry, coagulation etc.):')),
            _mkQ('moz_pl2', 'text',
              n('Інструментальні дослідження (ЕКГ, УЗД, рентген, МРТ, ендоскопія):', 'Instrumental investigations (ECG, ultrasound, X-ray, MRI, endoscopy):')),
            _mkQ('moz_pl3', 'text',
              n('Консультації спеціалістів:', 'Specialist consultations:')),

            // ── ПРИЗНАЧЕННЯ ───────────────────────────────────
            _mkQ('moz_rx1', 'text',
              n('Медикаментозне лікування (препарат — доза — кратність — тривалість):', 'Drug treatment (drug — dose — frequency — duration):')),
            _mkQ('moz_rx2', 'choice',
              n('Режим:', 'Regimen:'),
              n(['Амбулаторний', 'Стаціонарний', 'Ліжковий', 'Напівліжковий', 'Загальний'],
                ['Outpatient', 'Inpatient', 'Bed rest', 'Semi-bed rest', 'General'])),
            _mkQ('moz_rx3', 'text',
              n('Дієта (стіл № або опис обмежень):', 'Diet (table number or description of restrictions):')),
            _mkQ('moz_rx4', 'text',
              n('Рекомендації пацієнту (режим, фізична активність, спосіб життя):', 'Patient recommendations (regimen, physical activity, lifestyle):')),
            _mkQ('moz_rx5', 'text',
              n('Наступний прийом / явка (коли і до кого):', 'Next appointment (when and with whom):')),
            { id: 'q_moz_rx6', type: 'yesno', text: n('Листок непрацездатності (лікарняний):', 'Sick leave certificate:'), required: false,
              followUpYes: n('Дата відкриття та орієнтовний термін:', 'Opening date and estimated duration:'), followUpNo: '' },
            { id: 'q_moz_rx7', type: 'yesno', text: n('Направлення (до стаціонару, на консультацію):', 'Referral (to hospital, specialist):'), required: false,
              followUpYes: n('Куди та з якою метою:', 'Where and for what purpose:'), followUpNo: '' },
          ],
        },

        // ── ПОВТОРНИЙ ОГЛЯД ───────────────────────────────────
        {
          key: 'moz_003_followup',
          badge: 'narrow',
          name: n('Повторний огляд (МОЗ 003/о)', 'Follow-up Examination (MOH 003/o)'),
          desc: n('Скорочена форма для повторного прийому — динаміка, корекція лікування', 'Short form for follow-up — dynamics, treatment adjustment'),
          questions: [
            _mkQ('fu1', 'text',
              n('Активні скарги на момент повторного огляду:', 'Active complaints at follow-up:')),
            _mkQ('fu2', 'choice',
              n('Динаміка стану після попереднього огляду:', 'Condition dynamics since last visit:'),
              n(['Значне покращення', 'Покращення', 'Без змін', 'Погіршення'],
                ['Significant improvement', 'Improvement', 'No change', 'Worsening'])),
            { id: 'q_fu3', type: 'yesno', text: n('Чи виконував(ла) пацієнт попередні призначення:', 'Did patient follow previous prescriptions:'), required: false,
              followUpYes: '', followUpNo: n('Причина невиконання:', 'Reason for non-compliance:') },
            _mkQ('fu4', 'text',
              n('Ефект від призначеного лікування (що допомагає, побічні ефекти):', 'Effect of prescribed treatment (what helps, side effects):')),
            _mkQ('fu5', 'text',
              n('Результати обстежень з попереднього прийому (короткий опис):', 'Investigation results from last visit (brief description):')),
            _mkQ('fu6', 'text',
              n('АТ (мм рт.ст.), пульс (уд/хв) на цьому прийомі:', 'BP (mmHg), pulse (bpm) at this visit:')),
            _mkQ('fu7', 'text',
              n('Зміни в об\'єктивному статусі порівняно з попереднім оглядом:', 'Changes in objective status compared to last visit:')),
            _mkQ('fu8', 'text',
              n('Уточнений або остаточний діагноз за МКХ-10:', 'Refined or final diagnosis per ICD-10:')),
            _mkQ('fu9', 'text',
              n('Корекція лікування (зміна дози, додати / відмінити препарат):', 'Treatment adjustment (dose change, add / discontinue drug):')),
            _mkQ('fu10', 'text',
              n('Подальша тактика (наступний прийом, виписка, направлення, стаціонар):', 'Further management (next visit, discharge, referral, hospitalisation):')),
          ],
        },
      ],
    },

    // ════════════════════════════════════════════════════════
    // РЕШТА СПЕЦІАЛЬНОСТЕЙ (без змін)
    // ════════════════════════════════════════════════════════
    {
      icon: '👶', color: '#06d6a0',
      name: n('Педіатр', 'Pediatrician'),
      templates: [{
        key: 'ped_general',
        name: n('Педіатрія — Загальне', 'Pediatrics — General'),
        desc: n('Комплексний збір скарг (МОЗ ф. 025/о)', 'Comprehensive intake (MOH form 025/o)'),
        badge: 'main',
        questions: [
          _mkQ('p1',  'text',  n('Вік та стать дитини:', 'Age and sex of child:')),
          _mkQ('p2',  'text',  n('Маса тіла (кг) / зріст (см):', 'Weight (kg) / height (cm):')),
          _mkQ('p3',  'text',  n('Основна скарга (зі слів батьків/опікуна):', 'Chief complaint (per parent/guardian):')),
          _mkQ('p4',  'text',  n('Коли зʼявились симптоми, як розвивались:', 'Symptom onset and progression:')),
          _mkQ('p5',  'text',  n('Температура тіла (°C) та час вимірювання:', 'Body temperature (°C) and time measured:')),
          _mkQ('p6',  'scale', n('Загальний стан дитини (1 — дуже погано, 10 — чудово):', 'General condition (1–10):'), null, 1, 10),
          _mkQ('p7',  'yesno', n('Кашель:', 'Cough:'), yn),
          _mkQ('p8',  'text',  n('Характер кашлю (сухий/вологий, частота):', 'Cough type and frequency:')),
          _mkQ('p9',  'yesno', n('Нежить / закладеність носа:', 'Runny nose / nasal congestion:'), yn),
          _mkQ('p10', 'yesno', n('Блювання або зригування:', 'Vomiting or regurgitation:'), yn),
          _mkQ('p11', 'yesno', n('Порушення стільця (діарея / запор):', 'Stool changes (diarrhea / constipation):'), yn),
          _mkQ('p12', 'yesno', n('Висипання на шкірі:', 'Skin rash:'), yn),
          _mkQ('p13', 'yesno', n('Контакт з хворими (вдома, садок, школа):', 'Sick contact (home, nursery, school):'), yn),
          _mkQ('p14', 'text',  n('Щеплення за календарем (останнє, дата):', 'Vaccinations per schedule (last, date):')),
          _mkQ('p15', 'text',  n('Хронічні захворювання / спадковість:', 'Chronic conditions / hereditary history:')),
          _mkQ('p16', 'text',  n('Алергія (харчова, медикаментозна):', 'Allergies (food, drug):')),
          _mkQ('p17', 'text',  n('Препарати, що приймає зараз:', 'Current medications:')),
          _mkQ('p18', 'text',  n('Додаткові скарги або спостереження батьків:', 'Additional parental observations:')),
        ],
      }],
    },
    {
      icon: '❤️', color: '#ef4444',
      name: n('Кардіолог', 'Cardiologist'),
      templates: [{
        key: 'cardio',
        name: n('Кардіологія — Загальне', 'Cardiology — General'),
        desc: n('Стандартний кардіологічний анамнез (МОЗ ф. 025/о)', 'Standard cardiac intake (MOH form 025/o)'),
        badge: 'main',
        questions: [
          _mkQ('c1',  'text',  n('Основна скарга:', 'Main complaint:')),
          _mkQ('c2',  'text',  n('Біль у грудях — локалізація, характер, іррадіація:', 'Chest pain — location, character, radiation:')),
          _mkQ('c3',  'text',  n('Що провокує біль (навантаження, спокій, стрес):', 'Pain triggers (exertion, rest, stress):')),
          _mkQ('c4',  'text',  n('Задишка — при якому навантаженні виникає:', 'Dyspnoea — at what level of exertion:')),
          _mkQ('c5',  'yesno', n('Серцебиття / відчуття перебоїв у роботі серця:', 'Palpitations / irregular heartbeat:'), yn),
          _mkQ('c6',  'yesno', n('Набряки ніг:', 'Leg oedema:'), yn),
          _mkQ('c7',  'yesno', n('Непритомність або переднепритомні стани:', 'Syncope or pre-syncope:'), yn),
          _mkQ('c8',  'text',  n('АТ — останні виміри (дата, значення):', 'BP — recent readings (date, values):')),
          _mkQ('c9',  'text',  n('ЧСС у спокої (за останнім виміром):', 'Resting heart rate (last measured):')),
          _mkQ('c10', 'yesno', n('Паління (зараз або в минулому):', 'Smoking (current or past):'), yn),
          _mkQ('c11', 'text',  n('Алкоголь — частота та кількість:', 'Alcohol — frequency and amount:')),
          _mkQ('c12', 'yesno', n('Цукровий діабет:', 'Diabetes mellitus:'), yn),
          _mkQ('c13', 'text',  n('Ліпідний профіль (якщо відомий):', 'Lipid profile (if known):')),
          _mkQ('c14', 'text',  n('Перенесені серцево-судинні події (ІМ, ГПМК, ПКВ, АКШ):', 'Previous cardiovascular events (MI, stroke, PCI, CABG):')),
          _mkQ('c15', 'text',  n('Серцеві хвороби / раптова смерть у родичів (до 55 р.):', 'Family cardiac history / sudden death (under 55):')),
          _mkQ('c16', 'text',  n('Постійні препарати (назва, доза):', 'Regular medications (name, dose):')),
          _mkQ('c17', 'text',  n('Алергія на ліки:', 'Drug allergies:')),
          _mkQ('c18', 'text',  n('Останній ЕКГ / ЕхоКГ (дата, висновок):', 'Last ECG / Echo (date, findings):')),
        ],
      }],
    },
    {
      icon: '🧠', color: '#8b5cf6',
      name: n('Невролог', 'Neurologist'),
      templates: [{
        key: 'neuro',
        name: n('Неврологія — Загальне', 'Neurology — General'),
        desc: n('Базовий неврологічний анамнез (МОЗ ф. 025/о)', 'Standard neurological intake (MOH form 025/o)'),
        badge: 'main',
        questions: [
          _mkQ('n1',  'text',  n('Основна скарга:', 'Main complaint:')),
          _mkQ('n2',  'text',  n('Головний біль — локалізація, характер, тривалість, частота:', 'Headache — location, character, duration, frequency:')),
          _mkQ('n3',  'scale', n('Інтенсивність болю (1 — мінімальний, 10 — нестерпний):', 'Pain intensity (1–10):'), null, 1, 10),
          _mkQ('n4',  'text',  n('Що провокує / полегшує головний біль:', 'Headache triggers / relievers:')),
          _mkQ('n5',  'yesno', n('Нудота або блювання під час болю:', 'Nausea or vomiting with pain:'), yn),
          _mkQ('n6',  'yesno', n('Запаморочення:', 'Dizziness / vertigo:'), yn),
          _mkQ('n7',  'text',  n('Характер запаморочення (системне / несистемне):', 'Vertigo type (rotational / non-rotational):')),
          _mkQ('n8',  'yesno', n('Оніміння або слабкість у кінцівках:', 'Numbness or weakness in limbs:'), yn),
          _mkQ('n9',  'text',  n('Локалізація та час появи оніміння / слабкості:', 'Location and onset of numbness / weakness:')),
          _mkQ('n10', 'yesno', n('Судомні напади (в анамнезі або зараз):', 'Seizures (history or current):'), yn),
          _mkQ('n11', 'text',  n('Характер судом, їх частота та тривалість:', 'Seizure type, frequency and duration:')),
          _mkQ('n12', 'yesno', n('Порушення мови:', 'Speech disturbance:'), yn),
          _mkQ('n13', 'yesno', n("Порушення пам'яті або концентрації:", 'Memory or concentration problems:'), yn),
          _mkQ('n14', 'yesno', n('Порушення сну:', 'Sleep disturbances:'), yn),
          _mkQ('n15', 'yesno', n('Травми голови або хребта в анамнезі:', 'History of head or spinal injury:'), yn),
          _mkQ('n16', 'text',  n('Хронічні захворювання (АГ, ЦД, захворювання серця):', 'Chronic conditions (HTN, DM, heart disease):')),
          _mkQ('n17', 'text',  n('Препарати, що приймає зараз:', 'Current medications:')),
          _mkQ('n18', 'text',  n('Алергія на ліки:', 'Drug allergies:')),
          _mkQ('n19', 'text',  n('Останні нейровізуалізаційні дослідження (МРТ/КТ, дата):', 'Recent neuroimaging (MRI/CT, date):')),
        ],
      }],
    },
    {
      icon: '🔪', color: '#f59e0b',
      name: n('Хірург', 'Surgeon'),
      templates: [{
        key: 'surgery_general',
        name: n('Хірургія — Загальне', 'Surgery — General'),
        desc: n('Передопераційне опитування (МОЗ ф. 025/о)', 'Pre-operative intake (MOH form 025/o)'),
        badge: 'main',
        questions: [
          _mkQ('sg1',  'text',  n('Хірургічна проблема (скарга, локалізація):', 'Surgical complaint (complaint, location):')),
          _mkQ('sg2',  'text',  n('Тривалість симптомів та динаміка:', 'Duration and progression of symptoms:')),
          _mkQ('sg3',  'scale', n('Інтенсивність болю (1–10):', 'Pain intensity (1–10):'), null, 1, 10),
          _mkQ('sg4',  'text',  n('Характер болю (постійний, переймоподібний, пекучий):', 'Pain character (constant, cramping, burning):')),
          _mkQ('sg5',  'yesno', n('Гарячка (температура вище 37,5 °C):', 'Fever (above 37.5 °C):'), yn),
          _mkQ('sg6',  'yesno', n('Нудота або блювання:', 'Nausea or vomiting:'), yn),
          _mkQ('sg7',  'yesno', n('Порушення стільця / здуття живота:', 'Bowel changes / abdominal bloating:'), yn),
          _mkQ('sg8',  'yesno', n('Кровотеча або кривавий вміст у виділеннях:', 'Bleeding or bloody discharge:'), yn),
          _mkQ('sg9',  'text',  n('Попередні операції (що, коли, ускладнення):', 'Previous surgeries (what, when, complications):')),
          _mkQ('sg10', 'text',  n('Алергія на медикаменти / анестетики / латекс:', 'Allergies to medications / anaesthetics / latex:')),
          _mkQ('sg11', 'text',  n('Постійні препарати (включаючи антикоагулянти, аспірин):', 'Regular medications (incl. anticoagulants, aspirin):')),
          _mkQ('sg12', 'yesno', n('Паління:', 'Smoking:'), yn),
          _mkQ('sg13', 'yesno', n('Хронічні захворювання (серцево-судинні, ЦД, ниркова нед.):', 'Chronic conditions (CVD, DM, renal insufficiency):'), yn),
          _mkQ('sg14', 'text',  n('Остання їжа та рідина (дата й час):', 'Last food and fluid intake (date and time):')),
          _mkQ('sg15', 'text',  n('Додаткові обстеження (УЗД, КТ, аналізи — дати, висновки):', 'Additional tests (US, CT, labs — dates, findings):')),
        ],
      }],
    },
    {
      icon: '🌸', color: '#ec4899',
      name: n('Гінеколог', 'Gynaecologist'),
      templates: [{
        key: 'gyn_general',
        name: n('Гінекологія — Загальне', 'Gynaecology — General'),
        desc: n('Стандартний гінекологічний анамнез (МОЗ ф. 025/о)', 'Standard intake (MOH form 025/o)'),
        badge: 'main',
        questions: [
          _mkQ('gg1',  'text',  n('Основна скарга:', 'Main complaint:')),
          _mkQ('gg2',  'text',  n('Тривалість та динаміка симптомів:', 'Duration and progression of symptoms:')),
          _mkQ('gg3',  'text',  n('Дата останньої менструації (ДОМ):', 'Last menstrual period (LMP):')),
          _mkQ('gg4',  'text',  n('Тривалість та регулярність циклу (дні):', 'Cycle length and regularity (days):')),
          _mkQ('gg5',  'yesno', n('Болісна менструація (дисменорея):', 'Painful periods (dysmenorrhoea):'), yn),
          _mkQ('gg6',  'scale', n('Інтенсивність болю під час менструації (1–10):', 'Pain intensity during menstruation (1–10):'), null, 1, 10),
          _mkQ('gg7',  'yesno', n('Рясні або тривалі менструації (менорагія):', 'Heavy or prolonged periods (menorrhagia):'), yn),
          _mkQ('gg8',  'yesno', n('Кровомазання між менструаціями:', 'Intermenstrual spotting:'), yn),
          _mkQ('gg9',  'yesno', n('Виділення з піхви (патологічні):', 'Vaginal discharge (abnormal):'), yn),
          _mkQ('gg10', 'text',  n('Характер виділень (колір, запах, кількість):', 'Discharge character (colour, odour, amount):')),
          _mkQ('gg11', 'yesno', n('Біль під час статевого акту (диспареунія):', 'Pain during intercourse (dyspareunia):'), yn),
          _mkQ('gg12', 'text',  n('Метод контрацепції (зараз та в минулому):', 'Contraception method (current and past):')),
          _mkQ('gg13', 'text',  n('Вагітності / пологи / кесарів розтин / аборти:', 'Pregnancies / deliveries / C-sections / abortions:')),
          _mkQ('gg14', 'yesno', n('Можлива вагітність зараз:', 'Possible current pregnancy:'), yn),
          _mkQ('gg15', 'text',  n('Останній ПАП-тест / кольпоскопія (дата, результат):', 'Last Pap smear / colposcopy (date, result):')),
          _mkQ('gg16', 'text',  n('Останнє УЗД органів малого тазу (дата, висновок):', 'Last pelvic ultrasound (date, findings):')),
          _mkQ('gg17', 'text',  n('ІПСШ в анамнезі:', 'STI history:')),
          _mkQ('gg18', 'text',  n('Хронічні захворювання; препарати:', 'Chronic conditions; medications:')),
          _mkQ('gg19', 'text',  n('Алергія на ліки:', 'Drug allergies:')),
        ],
      }],
    },
    {
      icon: '🎀', color: '#ec4899',
      name: n('Мамолог', 'Mammologist'),
      templates: [{
        key: 'mammo_general',
        name: n('Мамологія — Загальне', 'Mammology — General'),
        desc: n('Стандартний мамологічний анамнез', 'Standard mammology intake'),
        badge: 'main',
        questions: [
          _mkQ('mm1',  'choice', n('Біль та дискомфорт в молочних залозах:', 'Breast pain/discomfort:'), ['Періодичний', 'Постійний', 'Відсутній']),
          _mkQ('mm2',  'choice', n('Біль односторонній чи двобічний:', 'Unilateral or bilateral:'), ['Односторонній (правий)', 'Односторонній (лівий)', 'Двобічний']),
          _mkQ('mm3',  'text',  n('Як довго турбує біль або дискомфорт:', 'Duration of pain/discomfort:')),
          _mkQ('mm4',  'text',  n("З чим пов'язуєте симптоми (цикл, стрес, травма):", 'Associated factors (cycle, stress, trauma):')),
          _mkQ('mm5',  'yesno', n('Чи знімається біль препаратами:', 'Does pain relief medication help:'), ['Так', 'Ні']),
          _mkQ('mm6',  'yesno', n('Зміна форми або кольору шкіри молочної залози:', 'Change in shape or skin colour:'), ['Так', 'Ні']),
          _mkQ('mm7',  'yesno', n('Наявність шкірних змін в ділянці декольте:', 'Skin changes in decollete area:'), ['Так', 'Ні']),
          _mkQ('mm8',  'yesno', n('Виділення із сосків:', 'Nipple discharge:'), ['Так', 'Ні']),
          _mkQ('mm9',  'text',  n('Характер виділень із сосків (якщо є):', 'Character of nipple discharge (if any):')),
          _mkQ('mm10', 'text',  n('Останнє обстеження молочної залози (дата, вид):', 'Last breast examination (date, type):')),
          _mkQ('mm11', 'text',  n('Вагітності / пологи / годування грудьми:', 'Pregnancies / deliveries / breastfeeding (months):')),
          _mkQ('mm12', 'yesno', n('Онкологія в родині:', 'Family history of cancer:'), ['Так', 'Ні']),
          _mkQ('mm13', 'text',  n('Шкідливі звички (паління, алкоголь, незручна білизна):', 'Harmful habits (smoking, alcohol, improper underwear):')),
          _mkQ('mm14', 'text',  n('Останній візит до гінеколога / дерматолога (дата):', 'Last visit to gynaecologist / dermatologist (date):')),
          _mkQ('mm15', 'text',  n('Наявність супутніх захворювань:', 'Comorbidities:')),
        ],
      }],
    },
    {
      icon: '🍽', color: '#06d6a0',
      name: n('Гастроентеролог', 'Gastroenterologist'),
      templates: [{
        key: 'gastro',
        name: n('Гастроентерологія — Загальне', 'Gastroenterology — General'),
        desc: n('Стандартний ШКТ анамнез (МОЗ ф. 025/о)', 'Standard GI intake (MOH form 025/o)'),
        badge: 'main',
        questions: [
          _mkQ('gi1',  'text',  n('Основна скарга:', 'Main GI complaint:')),
          _mkQ('gi2',  'text',  n('Локалізація та характер болю в животі:', 'Abdominal pain location and character:')),
          _mkQ('gi3',  'scale', n('Інтенсивність болю (1–10):', 'Pain intensity (1–10):'), null, 1, 10),
          _mkQ('gi4',  'text',  n("Зв'язок болю з їжею (до / після / незалежно):", 'Pain relation to meals (before / after / unrelated):')),
          _mkQ('gi5',  'yesno', n('Нудота:', 'Nausea:'), yn),
          _mkQ('gi6',  'yesno', n('Блювання (частота, вміст):', 'Vomiting (frequency, content):'), yn),
          _mkQ('gi7',  'yesno', n('Печія або відрижка:', 'Heartburn or belching:'), yn),
          _mkQ('gi8',  'yesno', n('Дисфагія (утруднене ковтання):', 'Dysphagia (difficulty swallowing):'), yn),
          _mkQ('gi9',  'text',  n('Характер стільця (частота, консистенція, колір):', 'Stool characteristics (frequency, consistency, colour):')),
          _mkQ('gi10', 'yesno', n('Кров або слиз у калі:', 'Blood or mucus in stool:'), yn),
          _mkQ('gi11', 'yesno', n('Здуття живота / метеоризм:', 'Abdominal bloating / flatulence:'), yn),
          _mkQ('gi12', 'text',  n('Зміна маси тіла (скільки кг за який час):', 'Weight change (how much, over how long):')),
          _mkQ('gi13', 'yesno', n('Жовтяниця або знебарвлений кал:', 'Jaundice or pale stool:'), yn),
          _mkQ('gi14', 'text',  n('Попередні ендоскопічні або УЗД дослідження (дата, результат):', 'Previous endoscopy or ultrasound (date, result):')),
          _mkQ('gi15', 'text',  n('Хронічні захворювання ШКТ в анамнезі:', 'GI conditions in history:')),
          _mkQ('gi16', 'yesno', n('Паління / вживання алкоголю:', 'Smoking / alcohol use:'), yn),
          _mkQ('gi17', 'text',  n('Препарати (особливо НПЗП, антибіотики, ІПП):', 'Medications (esp. NSAIDs, antibiotics, PPIs):')),
          _mkQ('gi18', 'text',  n('Алергія на ліки:', 'Drug allergies:')),
        ],
      }],
    },
    {
      icon: '💉', color: '#3b82f6',
      name: n('Ендокринолог', 'Endocrinologist'),
      templates: [{
        key: 'endo',
        name: n('Ендокринологія — Загальне', 'Endocrinology — General'),
        desc: n('Базовий ендокринологічний анамнез (МОЗ ф. 025/о)', 'Standard endocrine intake (MOH form 025/o)'),
        badge: 'main',
        questions: [
          _mkQ('e1',  'text',  n('Основна скарга:', 'Main complaint:')),
          _mkQ('e2',  'yesno', n('Цукровий діабет (діагностований):', 'Diagnosed diabetes mellitus:'), yn),
          _mkQ('e3',  'text',  n('Тип ЦД, стаж хвороби:', 'DM type, duration:')),
          _mkQ('e4',  'text',  n('Рівень глюкози натще та HbA1c (останні результати):', 'Fasting glucose & HbA1c (recent results):')),
          _mkQ('e5',  'yesno', n('Гіпоглікемічні епізоди:', 'Hypoglycaemic episodes:'), yn),
          _mkQ('e6',  'text',  n('Захворювання щитоподібної залози (діагноз, стаж):', 'Thyroid disease (diagnosis, duration):')),
          _mkQ('e7',  'text',  n('ТТГ, Т4 вільний (дата останнього аналізу):', 'TSH, free T4 (date of last test):')),
          _mkQ('e8',  'yesno', n('Збільшення щитоподібної залози або вузли:', 'Thyroid enlargement or nodules:'), yn),
          _mkQ('e9',  'text',  n('Зміна маси тіла (кількість кг, за який термін):', 'Weight change (kg, over what period):')),
          _mkQ('e10', 'yesno', n('Підвищена пітливість або непереносимість спеки/холоду:', 'Excessive sweating or heat/cold intolerance:'), yn),
          _mkQ('e11', 'yesno', n('Остеопороз або переломи в анамнезі:', 'Osteoporosis or fracture history:'), yn),
          _mkQ('e12', 'text',  n('Порушення менструального циклу або потенції:', 'Menstrual or erectile dysfunction:')),
          _mkQ('e13', 'text',  n('Спадковість (ендокринні захворювання у родичів):', 'Family history of endocrine disease:')),
          _mkQ('e14', 'text',  n('Препарати (інсулін, гормони, йод, стероїди):', 'Medications (insulin, hormones, iodine, steroids):')),
          _mkQ('e15', 'text',  n('Алергія на ліки:', 'Drug allergies:')),
        ],
      }],
    },
    {
      icon: '🩺', color: '#14b8a6',
      name: n('Терапевт', 'Therapist / GP'),
      templates: [{
        key: 'therapy',
        name: n('Терапія — Загальне', 'Therapy — General'),
        desc: n('Базовий терапевтичний анамнез (МОЗ ф. 025/о)', 'Standard GP intake (MOH form 025/o)'),
        badge: 'main',
        questions: [
          _mkQ('t1',  'text',  n('Опишіть детально все що турбує:', 'Describe all your current complaints in detail:')),
          _mkQ('t2',  'text',  n('Коли почались симптоми, як розвивались:', 'Symptom onset and progression:')),
          _mkQ('t3',  'scale', n('Загальне самопочуття (1 — дуже погано, 10 — відмінно):', 'Overall well-being (1–10):'), null, 1, 10),
          _mkQ('t4',  'text',  n('Температура тіла (якщо вимірювали):', 'Body temperature (if measured):')),
          _mkQ('t5',  'text',  n('Кашель — сухий чи вологий, коли почався:', 'Cough — dry or productive, onset:')),
          _mkQ('t6',  'yesno', n('Задишка або утруднене дихання:', 'Dyspnoea or difficulty breathing:'), yn),
          _mkQ('t7',  'yesno', n('Біль у горлі / закладеність носа:', 'Sore throat / nasal congestion:'), yn),
          _mkQ('t8',  'yesno', n('Нудота, блювання або порушення стільця:', 'Nausea, vomiting or bowel changes:'), yn),
          _mkQ('t9',  'text',  n('Які препарати вже приймали (назва, доза, ефект):', 'Medications already taken (name, dose, effect):')),
          _mkQ('t10', 'text',  n('Чи були обстеження (аналізи, рентген тощо):', 'Any tests done (labs, X-ray, etc.):')),
          _mkQ('t11', 'yesno', n('Хронічні захворювання:', 'Chronic conditions:'), yn),
          _mkQ('t12', 'text',  n('Перелік хронічних захворювань та постійних препаратів:', 'List of chronic conditions and regular medications:')),
          _mkQ('t13', 'yesno', n('Алергія на ліки:', 'Drug allergies:'), yn),
          _mkQ('t14', 'text',  n('Алергічні реакції (що, як проявляється):', 'Allergic reactions (what, how it manifests):')),
          _mkQ('t15', 'yesno', n('Паління або вживання алкоголю:', 'Smoking or alcohol use:'), yn),
          _mkQ('t16', 'yesno', n('Потрібен листок непрацездатності:', 'Sick leave certificate needed:'), yn),
        ],
      }],
    },
    {
      icon: '👁', color: '#0ea5e9',
      name: n('Офтальмолог', 'Ophthalmologist'),
      templates: [{
        key: 'ophth',
        name: n('Офтальмологія — Загальне', 'Ophthalmology — General'),
        desc: n('Стандартний офтальмологічний анамнез (МОЗ ф. 025/о)', 'Standard ophthalmic intake (MOH form 025/o)'),
        badge: 'main',
        questions: [
          _mkQ('o1',  'text',   n('Основна скарга:', 'Main complaint:')),
          _mkQ('o2',  'choice', n('Яке око турбує:', 'Affected eye:'), n(['Праве', 'Ліве', 'Обидва'], ['Right', 'Left', 'Both'])),
          _mkQ('o3',  'text',   n('Зміна гостроти зору (поступово / раптово):', 'Vision change (gradual / sudden):')),
          _mkQ('o4',  'yesno',  n('Біль або відчуття стороннього тіла в оці:', 'Eye pain or foreign body sensation:'), yn),
          _mkQ('o5',  'yesno',  n('Почервоніння очей:', 'Eye redness:'), yn),
          _mkQ('o6',  'yesno',  n('Виділення з очей (гнійні, слизисті):', 'Ocular discharge (purulent, mucous):'), yn),
          _mkQ('o7',  'yesno',  n('Сльозотеча:', 'Tearing / lacrimation:'), yn),
          _mkQ('o8',  'yesno',  n('Двоїння або спалахи перед очима:', 'Double vision or flashes of light:'), yn),
          _mkQ('o9',  'yesno',  n('Мушки, плями або пелена перед очима:', 'Floaters, spots or veil in vision:'), yn),
          _mkQ('o10', 'yesno',  n('Підвищена чутливість до світла (фотофобія):', 'Photophobia (light sensitivity):'), yn),
          _mkQ('o11', 'text',   n('Чи носите окуляри або лінзи (діоптрії):', 'Glasses or contact lenses (diopters):')),
          _mkQ('o12', 'text',   n('Попередні операції на очах (вид, дата):', 'Previous eye surgeries (type, date):')),
          _mkQ('o13', 'text',   n('Останній візит до офтальмолога (дата, результат):', 'Last ophthalmology visit (date, result):')),
          _mkQ('o14', 'yesno',  n('ЦД або АГ:', 'Diabetes or hypertension:'), yn),
          _mkQ('o15', 'text',   n('Очні краплі або препарати, що приймає зараз:', 'Current eye drops or medications:')),
          _mkQ('o16', 'text',   n('Алергія на ліки:', 'Drug allergies:')),
        ],
      }],
    },
    {
icon: '🚿', color: '#6366f1',      name: n('Уролог', 'Urologist'),
      templates: [{
        key: 'urology',
        name: n('Урологія — Загальне', 'Urology — General'),
        desc: n('Стандартний урологічний анамнез (МОЗ ф. 025/о)', 'Standard urological intake (MOH form 025/o)'),
        badge: 'main',
        questions: [
          _mkQ('u1',  'text',  n('Основна скарга:', 'Main complaint:')),
          _mkQ('u2',  'text',  n('Тривалість симптомів та динаміка:', 'Duration and progression of symptoms:')),
          _mkQ('u3',  'yesno', n('Болісне сечовипускання (дизурія):', 'Painful urination (dysuria):'), yn),
          _mkQ('u4',  'yesno', n('Часте сечовипускання (понад 8 разів на добу):', 'Frequent urination (more than 8 times/day):'), yn),
          _mkQ('u5',  'yesno', n('Нічне сечовипускання (ніктурія):', 'Nocturia:'), yn),
          _mkQ('u6',  'yesno', n('Ургентні позиви до сечовипускання:', 'Urgent urge to urinate:'), yn),
          _mkQ('u7',  'yesno', n('Кров у сечі (гематурія):', 'Blood in urine (haematuria):'), yn),
          _mkQ('u8',  'text',  n('Колір та прозорість сечі:', 'Urine colour and clarity:')),
          _mkQ('u9',  'yesno', n('Біль у поперековій ділянці або по ходу сечоводів:', 'Lumbar pain or pain along ureters:'), yn),
          _mkQ('u10', 'scale', n('Інтенсивність болю (1–10):', 'Pain intensity (1–10):'), null, 1, 10),
          _mkQ('u11', 'yesno', n('Виділення з уретри:', 'Urethral discharge:'), yn),
          _mkQ('u12', 'yesno', n('Утруднений початок або слабкий струмінь сечі (у чоловіків):', 'Hesitancy or weak stream (men):'), yn),
          _mkQ('u13', 'yesno', n('Нетримання сечі:', 'Urinary incontinence:'), yn),
          _mkQ('u14', 'yesno', n('Набряклість у ділянці яєчок або калитки (у чоловіків):', 'Scrotal or testicular swelling (men):'), yn),
          _mkQ('u15', 'text',  n('Попередні урологічні операції або захворювання:', 'Previous urological surgeries or conditions:')),
          _mkQ('u16', 'text',  n("Нирково-кам'яна хвороба в анамнезі:", 'History of urolithiasis:')),
          _mkQ('u17', 'text',  n('Загальний аналіз сечі (останній, дата):', 'Recent urinalysis (date, result):')),
          _mkQ('u18', 'text',  n('ПСА (для чоловіків, останній результат, дата):', 'PSA (men, recent result, date):')),
          _mkQ('u19', 'text',  n('Препарати, що приймає зараз:', 'Current medications:')),
          _mkQ('u20', 'text',  n('Алергія на ліки:', 'Drug allergies:')),
        ],
      }],
    },
    {
      icon: '🦴', color: '#d97706',
      name: n('Ортопед / Травматолог', 'Orthopaedist / Traumatologist'),
      templates: [{
        key: 'ortho',
        name: n('Ортопедія & Травматологія — Загальне', 'Orthopaedics & Traumatology — General'),
        desc: n('Стандартний ортопедичний анамнез (МОЗ ф. 025/о)', 'Standard orthopaedic intake (MOH form 025/o)'),
        badge: 'main',
        questions: [
          _mkQ('or1',  'text',  n('Основна скарга (локалізація, характер):', 'Main complaint (location, character):')),
          _mkQ('or2',  'text',  n('Обставини виникнення (травма, поступово, без причини):', 'Onset circumstances (trauma, gradual, unknown):')),
          _mkQ('or3',  'text',  n('Дата та механізм травми (якщо є):', 'Date and mechanism of injury (if applicable):')),
          _mkQ('or4',  'scale', n('Інтенсивність болю (1–10):', 'Pain intensity (1–10):'), null, 1, 10),
          _mkQ('or5',  'text',  n('Коли посилюється біль (рух, спокій, ніч):', 'Pain aggravated by (movement, rest, night):')),
          _mkQ('or6',  'yesno', n('Набряк або деформація ділянки:', 'Swelling or deformity:'), yn),
          _mkQ('or7',  'yesno', n('Обмеження рухів у суглобі / сегменті:', 'Limited range of motion:'), yn),
          _mkQ('or8',  'yesno', n('Хрускіт або клацання у суглобі:', 'Crepitation or clicking in joint:'), yn),
          _mkQ('or9',  'yesno', n('Оніміння або слабкість у кінцівці:', 'Numbness or weakness in limb:'), yn),
          _mkQ('or10', 'yesno', n('Попередні травми цієї самої ділянки:', 'Previous injuries to the same area:'), yn),
          _mkQ('or11', 'text',  n('Попередні операції на кістково-суглобовій системі:', 'Previous orthopaedic / trauma surgeries:')),
          _mkQ('or12', 'text',  n('Рентген або МРТ цієї ділянки (дата, висновок):', 'X-ray or MRI of the area (date, findings):')),
          _mkQ('or13', 'yesno', n('Остеопороз в анамнезі:', 'Osteoporosis history:'), yn),
          _mkQ('or14', 'text',  n('Хронічні захворювання (ревматоїдний артрит, подагра тощо):', 'Chronic conditions (RA, gout, etc.):')),
          _mkQ('or15', 'text',  n('Препарати (знеболювальні, стероїди, антикоагулянти):', 'Medications (analgesics, steroids, anticoagulants):')),
          _mkQ('or16', 'text',  n('Алергія на ліки:', 'Drug allergies:')),
          _mkQ('or17', 'text',  n('Професія та фізичне навантаження:', 'Occupation and physical activity level:')),
        ],
      }],
    },
    {
      icon: '🧴', color: '#f472b6',
      name: n('Дерматолог', 'Dermatologist'),
      templates: [{
        key: 'derm',
        name: n('Дерматологія — Загальне', 'Dermatology — General'),
        desc: n('Стандартний дерматологічний анамнез (МОЗ ф. 025/о)', 'Standard dermatological intake (MOH form 025/o)'),
        badge: 'main',
        questions: [
          _mkQ('d1',  'text',  n('Основна скарга:', 'Main complaint:')),
          _mkQ('d2',  'text',  n('Локалізація висипань / уражень:', 'Location of rash / lesions:')),
          _mkQ('d3',  'text',  n("Коли вперше з'явились та як розповсюджувались:", 'First appearance and spread pattern:')),
          _mkQ('d4',  'text',  n('Характер елементів (плями, папули, пухирі, лусочки):', 'Lesion type (macules, papules, vesicles, scales):')),
          _mkQ('d5',  'yesno', n('Свербіж:', 'Itching:'), yn),
          _mkQ('d6',  'scale', n('Інтенсивність свербіжу (1–10):', 'Itch intensity (1–10):'), null, 1, 10),
          _mkQ('d7',  'yesno', n('Печіння або болісність уражень:', 'Burning or pain at lesions:'), yn),
          _mkQ('d8',  'yesno', n('Мокнуття або виділення з уражень:', 'Oozing or discharge from lesions:'), yn),
          _mkQ('d9',  'text',  n('Чинники погіршення (сонце, вода, стрес, їжа):', 'Aggravating factors (sun, water, stress, food):')),
          _mkQ('d10', 'yesno', n('Контакт з алергенами або хімічними речовинами:', 'Contact with allergens or chemicals:'), yn),
          _mkQ('d11', 'yesno', n('Алергічні захворювання (атопія, астма, риніт):', 'Allergic conditions (atopy, asthma, rhinitis):'), yn),
          _mkQ('d12', 'text',  n('Шкірні захворювання в анамнезі або у родичів:', 'Skin conditions in personal or family history:')),
          _mkQ('d13', 'text',  n('Засоби догляду за шкірою, косметика:', 'Skin care products, cosmetics:')),
          _mkQ('d14', 'text',  n('Препарати, що приймає зараз (включно з місцевими):', 'Current medications (incl. topical):')),
          _mkQ('d15', 'text',  n('Алергія на ліки або речовини:', 'Drug or substance allergies:')),
          _mkQ('d16', 'yesno', n('Паління або вживання алкоголю:', 'Smoking or alcohol use:'), yn),
        ],
      }],
    },
    {
      icon: '😎', color: '#0891b2',
      name: n('Пульмонолог', 'Pulmonologist'),
      templates: [{
        key: 'pulmo',
        name: n('Пульмонологія — Загальне', 'Pulmonology — General'),
        desc: n('Стандартний пульмонологічний анамнез (МОЗ ф. 025/о)', 'Standard pulmonological intake (MOH form 025/o)'),
        badge: 'main',
        questions: [
          _mkQ('pl1',  'text',  n('Основна скарга:', 'Main complaint:')),
          _mkQ('pl2',  'text',  n('Кашель — характер (сухий / вологий), тривалість, частота:', 'Cough — type (dry/productive), duration, frequency:')),
          _mkQ('pl3',  'text',  n('Мокротиння — кількість, колір, консистенція:', 'Sputum — amount, colour, consistency:')),
          _mkQ('pl4',  'yesno', n('Кров у мокротинні (кровохаркання):', 'Blood in sputum (haemoptysis):'), yn),
          _mkQ('pl5',  'text',  n('Задишка — при якому навантаженні виникає (шкала MRC):', 'Dyspnoea — at what exertion level (MRC scale):')),
          _mkQ('pl6',  'yesno', n('Задишка у спокої:', 'Dyspnoea at rest:'), yn),
          _mkQ('pl7',  'yesno', n('Свистяче дихання (хрипи):', 'Wheezing:'), yn),
          _mkQ('pl8',  'yesno', n("Біль у грудній клітці, пов'язаний з диханням:", 'Chest pain related to breathing:'), yn),
          _mkQ('pl9',  'yesno', n('Нічний піт:', 'Night sweats:'), yn),
          _mkQ('pl10', 'yesno', n('Зниження маси тіла без видимої причини:', 'Unexplained weight loss:'), yn),
          _mkQ('pl11', 'yesno', n('Паління (зараз / в минулому):', 'Smoking (current / past):'), yn),
          _mkQ('pl12', 'text',  n('Стаж паління та кількість пачок на день (пачко-роки):', 'Smoking history and pack-years:')),
          _mkQ('pl13', 'text',  n('Професійний контакт із пилом, газами, азбестом:', 'Occupational exposure (dust, gases, asbestos):')),
          _mkQ('pl14', 'text',  n('Хронічні захворювання дихальної системи (астма, ХОЗЛ, ТБ):', 'Chronic respiratory conditions (asthma, COPD, TB):')),
          _mkQ('pl15', 'text',  n('Спірометрія або інші дослідження функції зовнішнього дихання:', 'Spirometry or other lung function tests (date, result):')),
          _mkQ('pl16', 'text',  n('Препарати (інгалятори, системні стероїди):', 'Medications (inhalers, systemic steroids):')),
          _mkQ('pl17', 'text',  n('Алергія на ліки:', 'Drug allergies:')),
        ],
      }],
    },
    {
      icon: '🧩', color: '#7c3aed',
      name: n('Психіатр / Психолог', 'Psychiatrist / Psychologist'),
      templates: [{
        key: 'psych',
        name: n('Психіатрія — Первинний прийом', 'Psychiatry — Initial Intake'),
        desc: n('Первинний психіатричний анамнез (МОЗ ф. 025/о)', 'Initial psychiatric intake (MOH form 025/o)'),
        badge: 'main',
        questions: [
          _mkQ('ps1',  'text',   n('Основна скарга (зі слів пацієнта):', "Main complaint (in patient's own words):")),
          _mkQ('ps2',  'text',   n('Коли вперше зʼявились симптоми:', 'First symptom onset:')),
          _mkQ('ps3',  'text',   n('Що передувало погіршенню (стреси, події, втрати):', 'Preceding events (stress, life events, losses):')),
          _mkQ('ps4',  'choice', n('Настрій переважно:', 'Predominant mood:'), n(['Знижений', 'Нормальний', 'Підвищений', 'Мінливий'], ['Low', 'Normal', 'Elevated', 'Variable'])),
          _mkQ('ps5',  'scale',  n('Рівень тривоги зараз (1–10):', 'Current anxiety level (1–10):'), null, 1, 10),
          _mkQ('ps6',  'scale',  n('Рівень депресії зараз (1–10):', 'Current depression level (1–10):'), null, 1, 10),
          _mkQ('ps7',  'yesno',  n('Порушення сну:', 'Sleep disturbances:'), yn),
          _mkQ('ps8',  'text',   n('Характер порушень сну (безсоння, надмірна сонливість, кошмари):', 'Sleep problem type (insomnia, hypersomnia, nightmares):')),
          _mkQ('ps9',  'yesno',  n('Зміна апетиту або маси тіла:', 'Appetite or weight change:'), yn),
          _mkQ('ps10', 'yesno',  n("Зниження концентрації або пам'яті:", 'Reduced concentration or memory:'), yn),
          _mkQ('ps11', 'yesno',  n('Думки про самоушкодження або суїцид:', 'Thoughts of self-harm or suicide:'), yn),
          _mkQ('ps12', 'yesno',  n('Вживання алкоголю, психоактивних речовин або медикаментів:', 'Alcohol, substance or medication misuse:'), yn),
          _mkQ('ps13', 'text',   n('Психіатричні діагнози в анамнезі:', 'Previous psychiatric diagnoses:')),
          _mkQ('ps14', 'text',   n('Попереднє лікування (психотерапія, медикаменти):', 'Previous treatment (psychotherapy, medications):')),
          _mkQ('ps15', 'text',   n('Психіатричні захворювання у родичів:', 'Family psychiatric history:')),
          _mkQ('ps16', 'text',   n('Поточна психіатрична/психологічна терапія або препарати:', 'Current psychiatric therapy or medications:')),
          _mkQ('ps17', 'text',   n('Алергія на ліки:', 'Drug allergies:')),
        ],
      }],
    },
    {
      icon: '👂', color: '#0d9488',
      name: n('ЛОР (Отоларинголог)', 'ENT (Otolaryngologist)'),
      templates: [{
        key: 'ent',
        name: n('ЛОР — Загальне', 'ENT — General'),
        desc: n('Стандартний ЛОР анамнез (МОЗ ф. 025/о)', 'Standard ENT intake (MOH form 025/o)'),
        badge: 'main',
        questions: [
          _mkQ('l1',  'text',   n('Основна скарга:', 'Main complaint:')),
          _mkQ('l2',  'choice', n('Яка ділянка турбує найбільше:', 'Most affected area:'), n(['Ніс / пазухи', 'Горло', 'Вухо (праве)', 'Вухо (ліве)', 'Обидва вуха', 'Декілька ділянок'], ['Nose / sinuses', 'Throat', 'Ear (right)', 'Ear (left)', 'Both ears', 'Multiple areas'])),
          _mkQ('l3',  'text',   n('Тривалість та динаміка симптомів:', 'Duration and progression of symptoms:')),
          _mkQ('l4',  'yesno',  n('Закладеність носа:', 'Nasal congestion:'), yn),
          _mkQ('l5',  'text',   n('Виділення з носа (колір, кількість):', 'Nasal discharge (colour, amount):')),
          _mkQ('l6',  'yesno',  n('Порушення нюху:', 'Loss of smell (hyposmia / anosmia):'), yn),
          _mkQ('l7',  'yesno',  n('Біль або тиск у ділянці пазух:', 'Sinus pain or pressure:'), yn),
          _mkQ('l8',  'yesno',  n('Біль у горлі або утруднене ковтання:', 'Sore throat or difficulty swallowing:'), yn),
          _mkQ('l9',  'yesno',  n('Охриплість голосу:', 'Hoarseness:'), yn),
          _mkQ('l10', 'yesno',  n('Зниження слуху:', 'Hearing loss:'), yn),
          _mkQ('l11', 'yesno',  n('Шум у вухах (тінітус):', 'Tinnitus:'), yn),
          _mkQ('l12', 'yesno',  n('Виділення з вуха:', 'Ear discharge:'), yn),
          _mkQ('l13', 'yesno',  n('Запаморочення системного характеру:', 'Vertigo (rotational dizziness):'), yn),
          _mkQ('l14', 'yesno',  n('Храпіння або апное уві сні:', 'Snoring or sleep apnoea:'), yn),
          _mkQ('l15', 'text',   n('Алергічні захворювання (алергічний риніт, бронхіальна астма):', 'Allergic conditions (allergic rhinitis, asthma):')),
          _mkQ('l16', 'text',   n('Попередні ЛОР операції (вид, дата):', 'Previous ENT surgeries (type, date):')),
          _mkQ('l17', 'text',   n('Препарати, що приймає зараз:', 'Current medications:')),
          _mkQ('l18', 'text',   n('Алергія на ліки:', 'Drug allergies:')),
        ],
      }],
    },
    {
icon: '🩺', color: '#dc2626',
      name: n('Нефролог', 'Nephrologist'),
      templates: [{
        key: 'nephro',
        name: n('Нефрологія — Загальне', 'Nephrology — General'),
        desc: n('Стандартний нефрологічний анамнез (МОЗ ф. 025/о)', 'Standard nephrological intake (MOH form 025/o)'),
        badge: 'main',
        questions: [
          _mkQ('nf1',  'text',  n('Основна скарга:', 'Main complaint:')),
          _mkQ('nf2',  'text',  n('Тривалість та динаміка симптомів:', 'Duration and progression:')),
          _mkQ('nf3',  'yesno', n('Набряки (обличчя, ноги, навколо очей — вранці):', 'Oedema (face, legs, periorbital — morning):'), yn),
          _mkQ('nf4',  'text',  n('Локалізація та час виникнення набряків:', 'Oedema location and timing:')),
          _mkQ('nf5',  'yesno', n('Зміна кількості сечі (зменшення або збільшення):', 'Change in urine output (decrease or increase):'), yn),
          _mkQ('nf6',  'text',  n('Приблизний добовий діурез (мл або склянки):', 'Approximate daily urine output (mL or cups):')),
          _mkQ('nf7',  'text',  n("Колір сечі (темна, бура, з кров'ю, піниста):", 'Urine colour (dark, brown, bloody, foamy):')),
          _mkQ('nf8',  'yesno', n('Болісне сечовипускання:', 'Painful urination:'), yn),
          _mkQ('nf9',  'yesno', n('Біль у поперековій ділянці:', 'Lumbar pain:'), yn),
          _mkQ('nf10', 'text',  n('АТ — останні виміри (дата, значення):', 'BP — recent readings (date, values):')),
          _mkQ('nf11', 'yesno', n('Цукровий діабет:', 'Diabetes mellitus:'), yn),
          _mkQ('nf12', 'text',  n('Рівень глюкози та HbA1c (якщо відомий):', 'Glucose & HbA1c (if known):')),
          _mkQ('nf13', 'yesno', n('Захворювання нирок у родичів (ниркова недостатність, полікістоз):', 'Family kidney disease (renal failure, polycystic):'), yn),
          _mkQ('nf14', 'text',  n('Попередні аналізи сечі або крові на функцію нирок (дата, результат):', 'Previous urinalysis or renal function labs (date, result):')),
          _mkQ('nf15', 'text',  n('УЗД нирок (дата, висновок):', 'Kidney ultrasound (date, findings):')),
          _mkQ('nf16', 'text',  n('Перенесені захворювання нирок / сечовивідних шляхів:', 'Previous kidney or urinary tract conditions:')),
          _mkQ('nf17', 'text',  n('Препарати (особливо НПЗП, інгібітори РАС, нефротоксичні):', 'Medications (esp. NSAIDs, RAS inhibitors, nephrotoxics):')),
          _mkQ('nf18', 'text',  n('Алергія на ліки:', 'Drug allergies:')),
        ],
      }],
    },
  ];
}

function _defaultSurveys() {
  const out = {};
  for (const spec of _specialtyTemplates()) {
    for (const tmpl of spec.templates) {
      out[tmpl.key] = { name: tmpl.name, questions: tmpl.questions };
    }
  }
  return out;
}
